version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Run the tests
          command: bundle exec rspec

      - run:
          name: Run Danger
          command: bundle exec danger
          when: always
